import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "var(--chatTypography)",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "var(--font-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        displayLarge: ["var(--text-display-size)", { lineHeight: "var(--text-display-line)", fontWeight: "var(--text-display-weight)", letterSpacing: "var(--text-display-tracking)" }],
        screenTitle: ["var(--text-screen-title-size)", { lineHeight: "var(--text-screen-title-line)", fontWeight: "var(--text-screen-title-weight)", letterSpacing: "var(--text-screen-title-tracking)" }],
        navigationTitle: ["var(--text-navigation-title-size)", { lineHeight: "var(--text-navigation-title-line)", fontWeight: "var(--text-navigation-title-weight)", letterSpacing: "var(--text-navigation-title-tracking)" }],
        conversationName: ["var(--text-conversation-name-size)", { lineHeight: "var(--text-conversation-name-line)", fontWeight: "var(--text-conversation-name-weight)", letterSpacing: "0" }],
        conversationPreview: ["var(--text-preview-size)", { lineHeight: "var(--text-preview-line)", fontWeight: "var(--text-preview-weight)", letterSpacing: "0" }],
        messageBody: ["var(--text-message-size)", { lineHeight: "var(--text-message-line)", fontWeight: "var(--text-message-weight)", letterSpacing: "0" }],
        messageInput: ["var(--text-input-size)", { lineHeight: "var(--text-input-line)", fontWeight: "var(--text-input-weight)", letterSpacing: "0" }],
        timestamp: ["var(--text-metadata-size)", { lineHeight: "var(--text-metadata-line)", fontWeight: "var(--text-metadata-weight)", letterSpacing: "0" }],
        messageMetadata: ["var(--text-metadata-size)", { lineHeight: "var(--text-metadata-line)", fontWeight: "var(--text-metadata-weight)", letterSpacing: "0" }],
        dateChip: ["var(--text-date-chip-size)", { lineHeight: "var(--text-date-chip-line)", fontWeight: "var(--text-date-chip-weight)", letterSpacing: "0" }],
        sectionLabel: ["var(--text-section-label-size)", { lineHeight: "var(--text-section-label-line)", fontWeight: "var(--text-section-label-weight)", letterSpacing: "0" }],
        settingsRowTitle: ["var(--text-settings-title-size)", { lineHeight: "var(--text-settings-title-line)", fontWeight: "var(--text-settings-title-weight)", letterSpacing: "0" }],
        settingsRowDescription: ["var(--text-settings-description-size)", { lineHeight: "var(--text-settings-description-line)", fontWeight: "var(--text-settings-description-weight)", letterSpacing: "0" }],
        buttonLabel: ["var(--text-button-size)", { lineHeight: "var(--text-button-line)", fontWeight: "var(--text-button-weight)", letterSpacing: "0" }],
        tabLabel: ["var(--text-tab-size)", { lineHeight: "var(--text-tab-line)", fontWeight: "var(--text-tab-weight)", letterSpacing: "0" }],
        badge: ["var(--text-badge-size)", { lineHeight: "var(--text-badge-line)", fontWeight: "var(--text-badge-weight)", letterSpacing: "0" }],
        quotedMessageSender: ["var(--text-quote-sender-size)", { lineHeight: "var(--text-quote-sender-line)", fontWeight: "var(--text-quote-sender-weight)", letterSpacing: "0" }],
        quotedMessageBody: ["var(--text-quote-body-size)", { lineHeight: "var(--text-quote-body-line)", fontWeight: "var(--text-quote-body-weight)", letterSpacing: "0" }],
        mediaCaption: ["var(--text-media-caption-size)", { lineHeight: "var(--text-media-caption-line)", fontWeight: "var(--text-media-caption-weight)", letterSpacing: "0" }],
        systemMessage: ["var(--text-system-message-size)", { lineHeight: "var(--text-system-message-line)", fontWeight: "var(--text-system-message-weight)", letterSpacing: "0" }],
        profileName: ["var(--text-profile-name-size)", { lineHeight: "var(--text-profile-name-line)", fontWeight: "var(--text-profile-name-weight)", letterSpacing: "var(--text-profile-name-tracking)" }],
        profileDescription: ["var(--text-media-caption-size)", { lineHeight: "var(--text-media-caption-line)", fontWeight: "var(--text-media-caption-weight)", letterSpacing: "0" }],
      },
      colors: {
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        primaryPressed: "rgb(var(--color-primary-pressed) / <alpha-value>)",
        primarySurface: "rgb(var(--color-primary-surface) / <alpha-value>)",
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        textPrimary: "rgb(var(--color-text-primary) / <alpha-value>)",
        textSecondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
        textDisabled: "rgb(var(--color-text-disabled) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        primaryHover: "rgb(var(--color-primary-pressed) / <alpha-value>)",
        primaryActive: "rgb(var(--color-primary-pressed) / <alpha-value>)",
        softBg: "rgb(var(--color-background) / <alpha-value>)",
        softSurface: "rgb(var(--color-primary-surface) / <alpha-value>)",
        disabledBg: "rgb(var(--color-background) / <alpha-value>)",
        disabledText: "rgb(var(--color-text-disabled) / <alpha-value>)",
        error: "rgb(var(--color-danger) / <alpha-value>)",
        errorBg: "rgb(var(--color-danger) / 0.10)",
        bg: "rgb(var(--color-background) / <alpha-value>)",
        section: "rgb(var(--color-background) / <alpha-value>)",
        card: "rgb(var(--color-surface) / <alpha-value>)",
        text: "rgb(var(--color-text-primary) / <alpha-value>)",
        muted: "rgb(var(--color-text-secondary) / <alpha-value>)",
        accent: "rgb(var(--color-primary) / <alpha-value>)",
        accentSoft: "rgb(var(--color-primary-surface) / <alpha-value>)",
      },
      boxShadow: {
        soft: "0 14px 34px rgba(15, 23, 42, 0.08)",
      },
      borderRadius: {
        soft: "16px",
      },
    },
  },
  plugins: [],
};

export default config;
